export const ICONS = [
	'accessibility-outline.svg' ,
	'journal-outline.svg' ,
	'accessibility-sharp.svg' ,
	'journal-sharp.svg' ,
	'accessibility.svg' ,
	'journal.svg' ,
	'add-circle-outline.svg' ,
	'key-outline.svg' ,
	'add-circle-sharp.svg' ,
	'key-sharp.svg' ,
	'add-circle.svg' ,
	'key.svg' ,
	'add-outline.svg' ,
	'keypad-outline.svg' ,
	'add-sharp.svg' ,
	'keypad-sharp.svg' ,
	'add.svg' ,
	'keypad.svg' ,
	'airplane-outline.svg' ,
	'language-outline.svg' ,
	'airplane-sharp.svg' ,
	'language-sharp.svg' ,
	'airplane.svg' ,
	'language.svg' ,
	'alarm-outline.svg' ,
	'laptop-outline.svg' ,
	'alarm-sharp.svg' ,
	'laptop-sharp.svg' ,
	'alarm.svg' ,
	'laptop.svg' ,
	'albums-outline.svg' ,
	'layers-outline.svg' ,
	'albums-sharp.svg' ,
	'layers-sharp.svg' ,
	'albums.svg' ,
	'layers.svg' ,
	'alert-circle-outline.svg' ,
	'leaf-outline.svg' ,
	'alert-circle-sharp.svg' ,
	'leaf-sharp.svg' ,
	'alert-circle.svg' ,
	'leaf.svg' ,
	'alert-outline.svg' ,
	'library-outline.svg' ,
	'alert-sharp.svg' ,
	'library-sharp.svg' ,
	'alert.svg' ,
	'library.svg' ,
	'american-football-outline.svg' ,
	'link-outline.svg' ,
	'american-football-sharp.svg' ,
	'link-sharp.svg' ,
	'american-football.svg' ,
	'link.svg' ,
	'analytics-outline.svg' ,
	'list-circle-outline.svg' ,
	'analytics-sharp.svg' ,
	'list-circle-sharp.svg' ,
	'analytics.svg' ,
	'list-circle.svg' ,
	'aperture-outline.svg' ,
	'list-outline.svg' ,
	'aperture-sharp.svg' ,
	'list-sharp.svg' ,
	'aperture.svg' ,
	'list.svg' ,
	'apps-outline.svg' ,
	'locate-outline.svg' ,
	'apps-sharp.svg' ,
	'locate-sharp.svg' ,
	'apps.svg' ,
	'locate.svg' ,
	'archive-outline.svg' ,
	'location-outline.svg' ,
	'archive-sharp.svg' ,
	'location-sharp.svg' ,
	'archive.svg' ,
	'location.svg' ,
	'arrow-back-circle-outline.svg' ,
	'lock-closed-outline.svg' ,
	'arrow-back-circle-sharp.svg' ,
	'lock-closed-sharp.svg' ,
	'arrow-back-circle.svg' ,
	'lock-closed.svg' ,
	'arrow-back-outline.svg' ,
	'lock-open-outline.svg' ,
	'arrow-back-sharp.svg' ,
	'lock-open-sharp.svg' ,
	'arrow-back.svg' ,
	'lock-open.svg' ,
	'arrow-down-circle-outline.svg' ,
	'log-in-outline.svg' ,
	'arrow-down-circle-sharp.svg' ,
	'log-in-sharp.svg' ,
	'arrow-down-circle.svg' ,
	'log-in.svg' ,
	'arrow-down-outline.svg' ,
	'log-out-outline.svg' ,
	'arrow-down-sharp.svg' ,
	'log-out-sharp.svg' ,
	'arrow-down.svg' ,
	'log-out.svg' ,
	'arrow-forward-circle-outline.svg' ,
	'logo-alipay.svg' ,
	'arrow-forward-circle-sharp.svg' ,
	'logo-amazon.svg' ,
	'arrow-forward-circle.svg' ,
	'logo-amplify.svg' ,
	'arrow-forward-outline.svg' ,
	'logo-android.svg' ,
	'arrow-forward-sharp.svg' ,
	'logo-angular.svg' ,
	'arrow-forward.svg' ,
	'logo-apple-appstore.svg' ,
	'arrow-redo-circle-outline.svg' ,
	'logo-apple-ar.svg' ,
	'arrow-redo-circle-sharp.svg' ,
	'logo-apple.svg' ,
	'arrow-redo-circle.svg' ,
	'logo-behance.svg' ,
	'arrow-redo-outline.svg' ,
	'logo-bitbucket.svg' ,
	'arrow-redo-sharp.svg' ,
	'logo-bitcoin.svg' ,
	'arrow-redo.svg' ,
	'logo-buffer.svg' ,
	'arrow-undo-circle-outline.svg' ,
	'logo-capacitor.svg' ,
	'arrow-undo-circle-sharp.svg' ,
	'logo-chrome.svg' ,
	'arrow-undo-circle.svg' ,
	'logo-closed-captioning.svg' ,
	'arrow-undo-outline.svg' ,
	'logo-codepen.svg' ,
	'arrow-undo-sharp.svg' ,
	'logo-css3.svg' ,
	'arrow-undo.svg' ,
	'logo-designernews.svg' ,
	'arrow-up-circle-outline.svg' ,
	'logo-deviantart.svg' ,
	'arrow-up-circle-sharp.svg' ,
	'logo-discord.svg' ,
	'arrow-up-circle.svg' ,
	'logo-docker.svg' ,
	'arrow-up-outline.svg' ,
	'logo-dribbble.svg' ,
	'arrow-up-sharp.svg' ,
	'logo-dropbox.svg' ,
	'arrow-up.svg' ,
	'logo-edge.svg' ,
	'at-circle-outline.svg' ,
	'logo-electron.svg' ,
	'at-circle-sharp.svg' ,
	'logo-euro.svg' ,
	'at-circle.svg' ,
	'logo-facebook.svg' ,
	'at-outline.svg' ,
	'logo-figma.svg' ,
	'at-sharp.svg' ,
	'logo-firebase.svg' ,
	'at.svg' ,
	'logo-firefox.svg' ,
	'attach-outline.svg' ,
	'logo-flickr.svg' ,
	'attach-sharp.svg' ,
	'logo-foursquare.svg' ,
	'attach.svg' ,
	'logo-github.svg' ,
	'backspace-outline.svg' ,
	'logo-gitlab.svg' ,
	'backspace-sharp.svg' ,
	'logo-google-playstore.svg' ,
	'backspace.svg' ,
	'logo-google.svg' ,
	'bag-add-outline.svg' ,
	'logo-hackernews.svg' ,
	'bag-add-sharp.svg' ,
	'logo-html5.svg' ,
	'bag-add.svg' ,
	'logo-instagram.svg' ,
	'bag-check-outline.svg' ,
	'logo-ionic.svg' ,
	'bag-check-sharp.svg' ,
	'logo-ionitron.svg' ,
	'bag-check.svg' ,
	'logo-javascript.svg' ,
	'bag-handle-outline.svg' ,
	'logo-laravel.svg' ,
	'bag-handle-sharp.svg' ,
	'logo-linkedin.svg' ,
	'bag-handle.svg' ,
	'logo-markdown.svg' ,
	'bag-outline.svg' ,
	'logo-mastodon.svg' ,
	'bag-remove-outline.svg' ,
	'logo-medium.svg' ,
	'bag-remove-sharp.svg' ,
	'logo-microsoft.svg' ,
	'bag-remove.svg' ,
	'logo-no-smoking.svg' ,
	'bag-sharp.svg' ,
	'logo-nodejs.svg' ,
	'bag.svg' ,
	'logo-npm.svg' ,
	'balloon-outline.svg' ,
	'logo-octocat.svg' ,
	'balloon-sharp.svg' ,
	'logo-paypal.svg' ,
	'balloon.svg' ,
	'logo-pinterest.svg' ,
	'ban-outline.svg' ,
	'logo-playstation.svg' ,
	'ban-sharp.svg' ,
	'logo-pwa.svg' ,
	'ban.svg' ,
	'logo-python.svg' ,
	'bandage-outline.svg' ,
	'logo-react.svg' ,
	'bandage-sharp.svg' ,
	'logo-reddit.svg' ,
	'bandage.svg' ,
	'logo-rss.svg' ,
	'bar-chart-outline.svg' ,
	'logo-sass.svg' ,
	'bar-chart-sharp.svg' ,
	'logo-skype.svg' ,
	'bar-chart.svg' ,
	'logo-slack.svg' ,
	'barbell-outline.svg' ,
	'logo-snapchat.svg' ,
	'barbell-sharp.svg' ,
	'logo-soundcloud.svg' ,
	'barbell.svg' ,
	'logo-stackoverflow.svg' ,
	'barcode-outline.svg' ,
	'logo-steam.svg' ,
	'barcode-sharp.svg' ,
	'logo-stencil.svg' ,
	'barcode.svg' ,
	'logo-tableau.svg' ,
	'baseball-outline.svg' ,
	'logo-tiktok.svg' ,
	'baseball-sharp.svg' ,
	'logo-tumblr.svg' ,
	'baseball.svg' ,
	'logo-tux.svg' ,
	'basket-outline.svg' ,
	'logo-twitch.svg' ,
	'basket-sharp.svg' ,
	'logo-twitter.svg' ,
	'basket.svg' ,
	'logo-usd.svg' ,
	'basketball-outline.svg' ,
	'logo-venmo.svg' ,
	'basketball-sharp.svg' ,
	'logo-vercel.svg' ,
	'basketball.svg' ,
	'logo-vimeo.svg' ,
	'battery-charging-outline.svg' ,
	'logo-vk.svg' ,
	'battery-charging-sharp.svg' ,
	'logo-vue.svg' ,
	'battery-charging.svg' ,
	'logo-web-component.svg' ,
	'battery-dead-outline.svg' ,
	'logo-wechat.svg' ,
	'battery-dead-sharp.svg' ,
	'logo-whatsapp.svg' ,
	'battery-dead.svg' ,
	'logo-windows.svg' ,
	'battery-full-outline.svg' ,
	'logo-wordpress.svg' ,
	'battery-full-sharp.svg' ,
	'logo-xbox.svg' ,
	'battery-full.svg' ,
	'logo-xing.svg' ,
	'battery-half-outline.svg' ,
	'logo-yahoo.svg' ,
	'battery-half-sharp.svg' ,
	'logo-yen.svg' ,
	'battery-half.svg' ,
	'logo-youtube.svg' ,
	'beaker-outline.svg' ,
	'magnet-outline.svg' ,
	'beaker-sharp.svg' ,
	'magnet-sharp.svg' ,
	'beaker.svg' ,
	'magnet.svg' ,
	'bed-outline.svg' ,
	'mail-open-outline.svg' ,
	'bed-sharp.svg' ,
	'mail-open-sharp.svg' ,
	'bed.svg' ,
	'mail-open.svg' ,
	'beer-outline.svg' ,
	'mail-outline.svg' ,
	'beer-sharp.svg' ,
	'mail-sharp.svg' ,
	'beer.svg' ,
	'mail-unread-outline.svg' ,
	'bicycle-outline.svg' ,
	'mail-unread-sharp.svg' ,
	'bicycle-sharp.svg' ,
	'mail-unread.svg' ,
	'bicycle.svg' ,
	'mail.svg' ,
	'bluetooth-outline.svg' ,
	'male-female-outline.svg' ,
	'bluetooth-sharp.svg' ,
	'male-female-sharp.svg' ,
	'bluetooth.svg' ,
	'male-female.svg' ,
	'boat-outline.svg' ,
	'male-outline.svg' ,
	'boat-sharp.svg' ,
	'male-sharp.svg' ,
	'boat.svg' ,
	'male.svg' ,
	'body-outline.svg' ,
	'man-outline.svg' ,
	'body-sharp.svg' ,
	'man-sharp.svg' ,
	'body.svg' ,
	'man.svg' ,
	'bonfire-outline.svg' ,
	'map-outline.svg' ,
	'bonfire-sharp.svg' ,
	'map-sharp.svg' ,
	'bonfire.svg' ,
	'map.svg' ,
	'book-outline.svg' ,
	'medal-outline.svg' ,
	'book-sharp.svg' ,
	'medal-sharp.svg' ,
	'book.svg' ,
	'medal.svg' ,
	'bookmark-outline.svg' ,
	'medical-outline.svg' ,
	'bookmark-sharp.svg' ,
	'medical-sharp.svg' ,
	'bookmark.svg' ,
	'medical.svg' ,
	'bookmarks-outline.svg' ,
	'medkit-outline.svg' ,
	'bookmarks-sharp.svg' ,
	'medkit-sharp.svg' ,
	'bookmarks.svg' ,
	'medkit.svg' ,
	'bowling-ball-outline.svg' ,
	'megaphone-outline.svg' ,
	'bowling-ball-sharp.svg' ,
	'megaphone-sharp.svg' ,
	'bowling-ball.svg' ,
	'megaphone.svg' ,
	'briefcase-outline.svg' ,
	'menu-outline.svg' ,
	'briefcase-sharp.svg' ,
	'menu-sharp.svg' ,
	'briefcase.svg' ,
	'menu.svg' ,
	'browsers-outline.svg' ,
	'mic-circle-outline.svg' ,
	'browsers-sharp.svg' ,
	'mic-circle-sharp.svg' ,
	'browsers.svg' ,
	'mic-circle.svg' ,
	'brush-outline.svg' ,
	'mic-off-circle-outline.svg' ,
	'brush-sharp.svg' ,
	'mic-off-circle-sharp.svg' ,
	'brush.svg' ,
	'mic-off-circle.svg' ,
	'bug-outline.svg' ,
	'mic-off-outline.svg' ,
	'bug-sharp.svg' ,
	'mic-off-sharp.svg' ,
	'bug.svg' ,
	'mic-off.svg' ,
	'build-outline.svg' ,
	'mic-outline.svg' ,
	'build-sharp.svg' ,
	'mic-sharp.svg' ,
	'build.svg' ,
	'mic.svg' ,
	'bulb-outline.svg' ,
	'moon-outline.svg' ,
	'bulb-sharp.svg' ,
	'moon-sharp.svg' ,
	'bulb.svg' ,
	'moon.svg' ,
	'bus-outline.svg' ,
	'move-outline.svg' ,
	'bus-sharp.svg' ,
	'move-sharp.svg' ,
	'bus.svg' ,
	'move.svg' ,
	'business-outline.svg' ,
	'musical-note-outline.svg' ,
	'business-sharp.svg' ,
	'musical-note-sharp.svg' ,
	'business.svg' ,
	'musical-note.svg' ,
	'cafe-outline.svg' ,
	'musical-notes-outline.svg' ,
	'cafe-sharp.svg' ,
	'musical-notes-sharp.svg' ,
	'cafe.svg' ,
	'musical-notes.svg' ,
	'calculator-outline.svg' ,
	'navigate-circle-outline.svg' ,
	'calculator-sharp.svg' ,
	'navigate-circle-sharp.svg' ,
	'calculator.svg' ,
	'navigate-circle.svg' ,
	'calendar-clear-outline.svg' ,
	'navigate-outline.svg' ,
	'calendar-clear-sharp.svg' ,
	'navigate-sharp.svg' ,
	'calendar-clear.svg' ,
	'navigate.svg' ,
	'calendar-number-outline.svg' ,
	'newspaper-outline.svg' ,
	'calendar-number-sharp.svg' ,
	'newspaper-sharp.svg' ,
	'calendar-number.svg' ,
	'newspaper.svg' ,
	'calendar-outline.svg' ,
	'notifications-circle-outline.svg' ,
	'calendar-sharp.svg' ,
	'notifications-circle-sharp.svg' ,
	'calendar.svg' ,
	'notifications-circle.svg' ,
	'call-outline.svg' ,
	'notifications-off-circle-outline.svg' ,
	'call-sharp.svg' ,
	'notifications-off-circle-sharp.svg' ,
	'call.svg' ,
	'notifications-off-circle.svg' ,
	'camera-outline.svg' ,
	'notifications-off-outline.svg' ,
	'camera-reverse-outline.svg' ,
	'notifications-off-sharp.svg' ,
	'camera-reverse-sharp.svg' ,
	'notifications-off.svg' ,
	'camera-reverse.svg' ,
	'notifications-outline.svg' ,
	'camera-sharp.svg' ,
	'notifications-sharp.svg' ,
	'camera.svg' ,
	'notifications.svg' ,
	'car-outline.svg' ,
	'nuclear-outline.svg' ,
	'car-sharp.svg' ,
	'nuclear-sharp.svg' ,
	'car-sport-outline.svg' ,
	'nuclear.svg' ,
	'car-sport-sharp.svg' ,
	'nutrition-outline.svg' ,
	'car-sport.svg' ,
	'nutrition-sharp.svg' ,
	'car.svg' ,
	'nutrition.svg' ,
	'card-outline.svg' ,
	'open-outline.svg' ,
	'card-sharp.svg' ,
	'open-sharp.svg' ,
	'card.svg' ,
	'open.svg' ,
	'caret-back-circle-outline.svg' ,
	'options-outline.svg' ,
	'caret-back-circle-sharp.svg' ,
	'options-sharp.svg' ,
	'caret-back-circle.svg' ,
	'options.svg' ,
	'caret-back-outline.svg' ,
	'paper-plane-outline.svg' ,
	'caret-back-sharp.svg' ,
	'paper-plane-sharp.svg' ,
	'caret-back.svg' ,
	'paper-plane.svg' ,
	'caret-down-circle-outline.svg' ,
	'partly-sunny-outline.svg' ,
	'caret-down-circle-sharp.svg' ,
	'partly-sunny-sharp.svg' ,
	'caret-down-circle.svg' ,
	'partly-sunny.svg' ,
	'caret-down-outline.svg' ,
	'pause-circle-outline.svg' ,
	'caret-down-sharp.svg' ,
	'pause-circle-sharp.svg' ,
	'caret-down.svg' ,
	'pause-circle.svg' ,
	'caret-forward-circle-outline.svg' ,
	'pause-outline.svg' ,
	'caret-forward-circle-sharp.svg' ,
	'pause-sharp.svg' ,
	'caret-forward-circle.svg' ,
	'pause.svg' ,
	'caret-forward-outline.svg' ,
	'paw-outline.svg' ,
	'caret-forward-sharp.svg' ,
	'paw-sharp.svg' ,
	'caret-forward.svg' ,
	'paw.svg' ,
	'caret-up-circle-outline.svg' ,
	'pencil-outline.svg' ,
	'caret-up-circle-sharp.svg' ,
	'pencil-sharp.svg' ,
	'caret-up-circle.svg' ,
	'pencil.svg' ,
	'caret-up-outline.svg' ,
	'people-circle-outline.svg' ,
	'caret-up-sharp.svg' ,
	'people-circle-sharp.svg' ,
	'caret-up.svg' ,
	'people-circle.svg' ,
	'cart-outline.svg' ,
	'people-outline.svg' ,
	'cart-sharp.svg' ,
	'people-sharp.svg' ,
	'cart.svg' ,
	'people.svg' ,
	'cash-outline.svg' ,
	'person-add-outline.svg' ,
	'cash-sharp.svg' ,
	'person-add-sharp.svg' ,
	'cash.svg' ,
	'person-add.svg' ,
	'cellular-outline.svg' ,
	'person-circle-outline.svg' ,
	'cellular-sharp.svg' ,
	'person-circle-sharp.svg' ,
	'cellular.svg' ,
	'person-circle.svg' ,
	'chatbox-ellipses-outline.svg' ,
	'person-outline.svg' ,
	'chatbox-ellipses-sharp.svg' ,
	'person-remove-outline.svg' ,
	'chatbox-ellipses.svg' ,
	'person-remove-sharp.svg' ,
	'chatbox-outline.svg' ,
	'person-remove.svg' ,
	'chatbox-sharp.svg' ,
	'person-sharp.svg' ,
	'chatbox.svg' ,
	'person.svg' ,
	'chatbubble-ellipses-outline.svg' ,
	'phone-landscape-outline.svg' ,
	'chatbubble-ellipses-sharp.svg' ,
	'phone-landscape-sharp.svg' ,
	'chatbubble-ellipses.svg' ,
	'phone-landscape.svg' ,
	'chatbubble-outline.svg' ,
	'phone-portrait-outline.svg' ,
	'chatbubble-sharp.svg' ,
	'phone-portrait-sharp.svg' ,
	'chatbubble.svg' ,
	'phone-portrait.svg' ,
	'chatbubbles-outline.svg' ,
	'pie-chart-outline.svg' ,
	'chatbubbles-sharp.svg' ,
	'pie-chart-sharp.svg' ,
	'chatbubbles.svg' ,
	'pie-chart.svg' ,
	'checkbox-outline.svg' ,
	'pin-outline.svg' ,
	'checkbox-sharp.svg' ,
	'pin-sharp.svg' ,
	'checkbox.svg' ,
	'pin.svg' ,
	'checkmark-circle-outline.svg' ,
	'pint-outline.svg' ,
	'checkmark-circle-sharp.svg' ,
	'pint-sharp.svg' ,
	'checkmark-circle.svg' ,
	'pint.svg' ,
	'checkmark-done-circle-outline.svg' ,
	'pizza-outline.svg' ,
	'checkmark-done-circle-sharp.svg' ,
	'pizza-sharp.svg' ,
	'checkmark-done-circle.svg' ,
	'pizza.svg' ,
	'checkmark-done-outline.svg' ,
	'planet-outline.svg' ,
	'checkmark-done-sharp.svg' ,
	'planet-sharp.svg' ,
	'checkmark-done.svg' ,
	'planet.svg' ,
	'checkmark-outline.svg' ,
	'play-back-circle-outline.svg' ,
	'checkmark-sharp.svg' ,
	'play-back-circle-sharp.svg' ,
	'checkmark.svg' ,
	'play-back-circle.svg' ,
	'chevron-back-circle-outline.svg' ,
	'play-back-outline.svg' ,
	'chevron-back-circle-sharp.svg' ,
	'play-back-sharp.svg' ,
	'chevron-back-circle.svg' ,
	'play-back.svg' ,
	'chevron-back-outline.svg' ,
	'play-circle-outline.svg' ,
	'chevron-back-sharp.svg' ,
	'play-circle-sharp.svg' ,
	'chevron-back.svg' ,
	'play-circle.svg' ,
	'chevron-down-circle-outline.svg' ,
	'play-forward-circle-outline.svg' ,
	'chevron-down-circle-sharp.svg' ,
	'play-forward-circle-sharp.svg' ,
	'chevron-down-circle.svg' ,
	'play-forward-circle.svg' ,
	'chevron-down-outline.svg' ,
	'play-forward-outline.svg' ,
	'chevron-down-sharp.svg' ,
	'play-forward-sharp.svg' ,
	'chevron-down.svg' ,
	'play-forward.svg' ,
	'chevron-forward-circle-outline.svg' ,
	'play-outline.svg' ,
	'chevron-forward-circle-sharp.svg' ,
	'play-sharp.svg' ,
	'chevron-forward-circle.svg' ,
	'play-skip-back-circle-outline.svg' ,
	'chevron-forward-outline.svg' ,
	'play-skip-back-circle-sharp.svg' ,
	'chevron-forward-sharp.svg' ,
	'play-skip-back-circle.svg' ,
	'chevron-forward.svg' ,
	'play-skip-back-outline.svg' ,
	'chevron-up-circle-outline.svg' ,
	'play-skip-back-sharp.svg' ,
	'chevron-up-circle-sharp.svg' ,
	'play-skip-back.svg' ,
	'chevron-up-circle.svg' ,
	'play-skip-forward-circle-outline.svg' ,
	'chevron-up-outline.svg' ,
	'play-skip-forward-circle-sharp.svg' ,
	'chevron-up-sharp.svg' ,
	'play-skip-forward-circle.svg' ,
	'chevron-up.svg' ,
	'play-skip-forward-outline.svg' ,
	'clipboard-outline.svg' ,
	'play-skip-forward-sharp.svg' ,
	'clipboard-sharp.svg' ,
	'play-skip-forward.svg' ,
	'clipboard.svg' ,
	'play.svg' ,
	'close-circle-outline.svg' ,
	'podium-outline.svg' ,
	'close-circle-sharp.svg' ,
	'podium-sharp.svg' ,
	'close-circle.svg' ,
	'podium.svg' ,
	'close-outline.svg' ,
	'power-outline.svg' ,
	'close-sharp.svg' ,
	'power-sharp.svg' ,
	'close.svg' ,
	'power.svg' ,
	'cloud-circle-outline.svg' ,
	'pricetag-outline.svg' ,
	'cloud-circle-sharp.svg' ,
	'pricetag-sharp.svg' ,
	'cloud-circle.svg' ,
	'pricetag.svg' ,
	'cloud-done-outline.svg' ,
	'pricetags-outline.svg' ,
	'cloud-done-sharp.svg' ,
	'pricetags-sharp.svg' ,
	'cloud-done.svg' ,
	'pricetags.svg' ,
	'cloud-download-outline.svg' ,
	'print-outline.svg' ,
	'cloud-download-sharp.svg' ,
	'print-sharp.svg' ,
	'cloud-download.svg' ,
	'print.svg' ,
	'cloud-offline-outline.svg' ,
	'prism-outline.svg' ,
	'cloud-offline-sharp.svg' ,
	'prism-sharp.svg' ,
	'cloud-offline.svg' ,
	'prism.svg' ,
	'cloud-outline.svg' ,
	'pulse-outline.svg' ,
	'cloud-sharp.svg' ,
	'pulse-sharp.svg' ,
	'cloud-upload-outline.svg' ,
	'pulse.svg' ,
	'cloud-upload-sharp.svg' ,
	'push-outline.svg' ,
	'cloud-upload.svg' ,
	'push-sharp.svg' ,
	'cloud.svg' ,
	'push.svg' ,
	'cloudy-night-outline.svg' ,
	'qr-code-outline.svg' ,
	'cloudy-night-sharp.svg' ,
	'qr-code-sharp.svg' ,
	'cloudy-night.svg' ,
	'qr-code.svg' ,
	'cloudy-outline.svg' ,
	'radio-button-off-outline.svg' ,
	'cloudy-sharp.svg' ,
	'radio-button-off-sharp.svg' ,
	'cloudy.svg' ,
	'radio-button-off.svg' ,
	'code-download-outline.svg' ,
	'radio-button-on-outline.svg' ,
	'code-download-sharp.svg' ,
	'radio-button-on-sharp.svg' ,
	'code-download.svg' ,
	'radio-button-on.svg' ,
	'code-outline.svg' ,
	'radio-outline.svg' ,
	'code-sharp.svg' ,
	'radio-sharp.svg' ,
	'code-slash-outline.svg' ,
	'radio.svg' ,
	'code-slash-sharp.svg' ,
	'rainy-outline.svg' ,
	'code-slash.svg' ,
	'rainy-sharp.svg' ,
	'code-working-outline.svg' ,
	'rainy.svg' ,
	'code-working-sharp.svg' ,
	'reader-outline.svg' ,
	'code-working.svg' ,
	'reader-sharp.svg' ,
	'code.svg' ,
	'reader.svg' ,
	'cog-outline.svg' ,
	'receipt-outline.svg' ,
	'cog-sharp.svg' ,
	'receipt-sharp.svg' ,
	'cog.svg' ,
	'receipt.svg' ,
	'color-fill-outline.svg' ,
	'recording-outline.svg' ,
	'color-fill-sharp.svg' ,
	'recording-sharp.svg' ,
	'color-fill.svg' ,
	'recording.svg' ,
	'color-filter-outline.svg' ,
	'refresh-circle-outline.svg' ,
	'color-filter-sharp.svg' ,
	'refresh-circle-sharp.svg' ,
	'color-filter.svg' ,
	'refresh-circle.svg' ,
	'color-palette-outline.svg' ,
	'refresh-outline.svg' ,
	'color-palette-sharp.svg' ,
	'refresh-sharp.svg' ,
	'color-palette.svg' ,
	'refresh.svg' ,
	'color-wand-outline.svg' ,
	'reload-circle-outline.svg' ,
	'color-wand-sharp.svg' ,
	'reload-circle-sharp.svg' ,
	'color-wand.svg' ,
	'reload-circle.svg' ,
	'compass-outline.svg' ,
	'reload-outline.svg' ,
	'compass-sharp.svg' ,
	'reload-sharp.svg' ,
	'compass.svg' ,
	'reload.svg' ,
	'construct-outline.svg' ,
	'remove-circle-outline.svg' ,
	'construct-sharp.svg' ,
	'remove-circle-sharp.svg' ,
	'construct.svg' ,
	'remove-circle.svg' ,
	'contract-outline.svg' ,
	'remove-outline.svg' ,
	'contract-sharp.svg' ,
	'remove-sharp.svg' ,
	'contract.svg' ,
	'remove.svg' ,
	'contrast-outline.svg' ,
	'reorder-four-outline.svg' ,
	'contrast-sharp.svg' ,
	'reorder-four-sharp.svg' ,
	'contrast.svg' ,
	'reorder-four.svg' ,
	'copy-outline.svg' ,
	'reorder-three-outline.svg' ,
	'copy-sharp.svg' ,
	'reorder-three-sharp.svg' ,
	'copy.svg' ,
	'reorder-three.svg' ,
	'create-outline.svg' ,
	'reorder-two-outline.svg' ,
	'create-sharp.svg' ,
	'reorder-two-sharp.svg' ,
	'create.svg' ,
	'reorder-two.svg' ,
	'crop-outline.svg' ,
	'repeat-outline.svg' ,
	'crop-sharp.svg' ,
	'repeat-sharp.svg' ,
	'crop.svg' ,
	'repeat.svg' ,
	'cube-outline.svg' ,
	'resize-outline.svg' ,
	'cube-sharp.svg' ,
	'resize-sharp.svg' ,
	'cube.svg' ,
	'resize.svg' ,
	'cut-outline.svg' ,
	'restaurant-outline.svg' ,
	'cut-sharp.svg' ,
	'restaurant-sharp.svg' ,
	'cut.svg' ,
	'restaurant.svg' ,
	'desktop-outline.svg' ,
	'return-down-back-outline.svg' ,
	'desktop-sharp.svg' ,
	'return-down-back-sharp.svg' ,
	'desktop.svg' ,
	'return-down-back.svg' ,
	'diamond-outline.svg' ,
	'return-down-forward-outline.svg' ,
	'diamond-sharp.svg' ,
	'return-down-forward-sharp.svg' ,
	'diamond.svg' ,
	'return-down-forward.svg' ,
	'dice-outline.svg' ,
	'return-up-back-outline.svg' ,
	'dice-sharp.svg' ,
	'return-up-back-sharp.svg' ,
	'dice.svg' ,
	'return-up-back.svg' ,
	'disc-outline.svg' ,
	'return-up-forward-outline.svg' ,
	'disc-sharp.svg' ,
	'return-up-forward-sharp.svg' ,
	'disc.svg' ,
	'return-up-forward.svg' ,
	'document-attach-outline.svg' ,
	'ribbon-outline.svg' ,
	'document-attach-sharp.svg' ,
	'ribbon-sharp.svg' ,
	'document-attach.svg' ,
	'ribbon.svg' ,
	'document-lock-outline.svg' ,
	'rocket-outline.svg' ,
	'document-lock-sharp.svg' ,
	'rocket-sharp.svg' ,
	'document-lock.svg' ,
	'rocket.svg' ,
	'document-outline.svg' ,
	'rose-outline.svg' ,
	'document-sharp.svg' ,
	'rose-sharp.svg' ,
	'document-text-outline.svg' ,
	'rose.svg' ,
	'document-text-sharp.svg' ,
	'sad-outline.svg' ,
	'document-text.svg' ,
	'sad-sharp.svg' ,
	'document.svg' ,
	'sad.svg' ,
	'documents-outline.svg' ,
	'save-outline.svg' ,
	'documents-sharp.svg' ,
	'save-sharp.svg' ,
	'documents.svg' ,
	'save.svg' ,
	'download-outline.svg' ,
	'scale-outline.svg' ,
	'download-sharp.svg' ,
	'scale-sharp.svg' ,
	'download.svg' ,
	'scale.svg' ,
	'duplicate-outline.svg' ,
	'scan-circle-outline.svg' ,
	'duplicate-sharp.svg' ,
	'scan-circle-sharp.svg' ,
	'duplicate.svg' ,
	'scan-circle.svg' ,
	'ear-outline.svg' ,
	'scan-outline.svg' ,
	'ear-sharp.svg' ,
	'scan-sharp.svg' ,
	'ear.svg' ,
	'scan.svg' ,
	'earth-outline.svg' ,
	'school-outline.svg' ,
	'earth-sharp.svg' ,
	'school-sharp.svg' ,
	'earth.svg' ,
	'school.svg' ,
	'easel-outline.svg' ,
	'search-circle-outline.svg' ,
	'easel-sharp.svg' ,
	'search-circle-sharp.svg' ,
	'easel.svg' ,
	'search-circle.svg' ,
	'egg-outline.svg' ,
	'search-outline.svg' ,
	'egg-sharp.svg' ,
	'search-sharp.svg' ,
	'egg.svg' ,
	'search.svg' ,
	'ellipse-outline.svg' ,
	'send-outline.svg' ,
	'ellipse-sharp.svg' ,
	'send-sharp.svg' ,
	'ellipse.svg' ,
	'send.svg' ,
	'ellipsis-horizontal-circle-outline.svg' ,
	'server-outline.svg' ,
	'ellipsis-horizontal-circle-sharp.svg' ,
	'server-sharp.svg' ,
	'ellipsis-horizontal-circle.svg' ,
	'server.svg' ,
	'ellipsis-horizontal-outline.svg' ,
	'settings-outline.svg' ,
	'ellipsis-horizontal-sharp.svg' ,
	'settings-sharp.svg' ,
	'ellipsis-horizontal.svg' ,
	'settings.svg' ,
	'ellipsis-vertical-circle-outline.svg' ,
	'shapes-outline.svg' ,
	'ellipsis-vertical-circle-sharp.svg' ,
	'shapes-sharp.svg' ,
	'ellipsis-vertical-circle.svg' ,
	'shapes.svg' ,
	'ellipsis-vertical-outline.svg' ,
	'share-outline.svg' ,
	'ellipsis-vertical-sharp.svg' ,
	'share-sharp.svg' ,
	'ellipsis-vertical.svg' ,
	'share-social-outline.svg' ,
	'enter-outline.svg' ,
	'share-social-sharp.svg' ,
	'enter-sharp.svg' ,
	'share-social.svg' ,
	'enter.svg' ,
	'share.svg' ,
	'exit-outline.svg' ,
	'shield-checkmark-outline.svg' ,
	'exit-sharp.svg' ,
	'shield-checkmark-sharp.svg' ,
	'exit.svg' ,
	'shield-checkmark.svg' ,
	'expand-outline.svg' ,
	'shield-half-outline.svg' ,
	'expand-sharp.svg' ,
	'shield-half-sharp.svg' ,
	'expand.svg' ,
	'shield-half.svg' ,
	'extension-puzzle-outline.svg' ,
	'shield-outline.svg' ,
	'extension-puzzle-sharp.svg' ,
	'shield-sharp.svg' ,
	'extension-puzzle.svg' ,
	'shield.svg' ,
	'eye-off-outline.svg' ,
	'shirt-outline.svg' ,
	'eye-off-sharp.svg' ,
	'shirt-sharp.svg' ,
	'eye-off.svg' ,
	'shirt.svg' ,
	'eye-outline.svg' ,
	'shuffle-outline.svg' ,
	'eye-sharp.svg' ,
	'shuffle-sharp.svg' ,
	'eye.svg' ,
	'shuffle.svg' ,
	'eyedrop-outline.svg' ,
	'skull-outline.svg' ,
	'eyedrop-sharp.svg' ,
	'skull-sharp.svg' ,
	'eyedrop.svg' ,
	'skull.svg' ,
	'fast-food-outline.svg' ,
	'snow-outline.svg' ,
	'fast-food-sharp.svg' ,
	'snow-sharp.svg' ,
	'fast-food.svg' ,
	'snow.svg' ,
	'female-outline.svg' ,
	'sparkles-outline.svg' ,
	'female-sharp.svg' ,
	'sparkles-sharp.svg' ,
	'female.svg' ,
	'sparkles.svg' ,
	'file-tray-full-outline.svg' ,
	'speedometer-outline.svg' ,
	'file-tray-full-sharp.svg' ,
	'speedometer-sharp.svg' ,
	'file-tray-full.svg' ,
	'speedometer.svg' ,
	'file-tray-outline.svg' ,
	'square-outline.svg' ,
	'file-tray-sharp.svg' ,
	'square-sharp.svg' ,
	'file-tray-stacked-outline.svg' ,
	'square.svg' ,
	'file-tray-stacked-sharp.svg' ,
	'star-half-outline.svg' ,
	'file-tray-stacked.svg' ,
	'star-half-sharp.svg' ,
	'file-tray.svg' ,
	'star-half.svg' ,
	'film-outline.svg' ,
	'star-outline.svg' ,
	'film-sharp.svg' ,
	'star-sharp.svg' ,
	'film.svg' ,
	'star.svg' ,
	'filter-circle-outline.svg' ,
	'stats-chart-outline.svg' ,
	'filter-circle-sharp.svg' ,
	'stats-chart-sharp.svg' ,
	'filter-circle.svg' ,
	'stats-chart.svg' ,
	'filter-outline.svg' ,
	'stop-circle-outline.svg' ,
	'filter-sharp.svg' ,
	'stop-circle-sharp.svg' ,
	'filter.svg' ,
	'stop-circle.svg' ,
	'finger-print-outline.svg' ,
	'stop-outline.svg' ,
	'finger-print-sharp.svg' ,
	'stop-sharp.svg' ,
	'finger-print.svg' ,
	'stop.svg' ,
	'fish-outline.svg' ,
	'stopwatch-outline.svg' ,
	'fish-sharp.svg' ,
	'stopwatch-sharp.svg' ,
	'fish.svg' ,
	'stopwatch.svg' ,
	'fitness-outline.svg' ,
	'storefront-outline.svg' ,
	'fitness-sharp.svg' ,
	'storefront-sharp.svg' ,
	'fitness.svg' ,
	'storefront.svg' ,
	'flag-outline.svg' ,
	'subway-outline.svg' ,
	'flag-sharp.svg' ,
	'subway-sharp.svg' ,
	'flag.svg' ,
	'subway.svg' ,
	'flame-outline.svg' ,
	'sunny-outline.svg' ,
	'flame-sharp.svg' ,
	'sunny-sharp.svg' ,
	'flame.svg' ,
	'sunny.svg' ,
	'flash-off-outline.svg' ,
	'swap-horizontal-outline.svg' ,
	'flash-off-sharp.svg' ,
	'swap-horizontal-sharp.svg' ,
	'flash-off.svg' ,
	'swap-horizontal.svg' ,
	'flash-outline.svg' ,
	'swap-vertical-outline.svg' ,
	'flash-sharp.svg' ,
	'swap-vertical-sharp.svg' ,
	'flash.svg' ,
	'swap-vertical.svg' ,
	'flashlight-outline.svg' ,
	'sync-circle-outline.svg' ,
	'flashlight-sharp.svg' ,
	'sync-circle-sharp.svg' ,
	'flashlight.svg' ,
	'sync-circle.svg' ,
	'flask-outline.svg' ,
	'sync-outline.svg' ,
	'flask-sharp.svg' ,
	'sync-sharp.svg' ,
	'flask.svg' ,
	'sync.svg' ,
	'flower-outline.svg' ,
	'tablet-landscape-outline.svg' ,
	'flower-sharp.svg' ,
	'tablet-landscape-sharp.svg' ,
	'flower.svg' ,
	'tablet-landscape.svg' ,
	'folder-open-outline.svg' ,
	'tablet-portrait-outline.svg' ,
	'folder-open-sharp.svg' ,
	'tablet-portrait-sharp.svg' ,
	'folder-open.svg' ,
	'tablet-portrait.svg' ,
	'folder-outline.svg' ,
	'telescope-outline.svg' ,
	'folder-sharp.svg' ,
	'telescope-sharp.svg' ,
	'folder.svg' ,
	'telescope.svg' ,
	'football-outline.svg' ,
	'tennisball-outline.svg' ,
	'football-sharp.svg' ,
	'tennisball-sharp.svg' ,
	'football.svg' ,
	'tennisball.svg' ,
	'footsteps-outline.svg' ,
	'terminal-outline.svg' ,
	'footsteps-sharp.svg' ,
	'terminal-sharp.svg' ,
	'footsteps.svg' ,
	'terminal.svg' ,
	'funnel-outline.svg' ,
	'text-outline.svg' ,
	'funnel-sharp.svg' ,
	'text-sharp.svg' ,
	'funnel.svg' ,
	'text.svg' ,
	'game-controller-outline.svg' ,
	'thermometer-outline.svg' ,
	'game-controller-sharp.svg' ,
	'thermometer-sharp.svg' ,
	'game-controller.svg' ,
	'thermometer.svg' ,
	'gift-outline.svg' ,
	'thumbs-down-outline.svg' ,
	'gift-sharp.svg' ,
	'thumbs-down-sharp.svg' ,
	'gift.svg' ,
	'thumbs-down.svg' ,
	'git-branch-outline.svg' ,
	'thumbs-up-outline.svg' ,
	'git-branch-sharp.svg' ,
	'thumbs-up-sharp.svg' ,
	'git-branch.svg' ,
	'thumbs-up.svg' ,
	'git-commit-outline.svg' ,
	'thunderstorm-outline.svg' ,
	'git-commit-sharp.svg' ,
	'thunderstorm-sharp.svg' ,
	'git-commit.svg' ,
	'thunderstorm.svg' ,
	'git-compare-outline.svg' ,
	'ticket-outline.svg' ,
	'git-compare-sharp.svg' ,
	'ticket-sharp.svg' ,
	'git-compare.svg' ,
	'ticket.svg' ,
	'git-merge-outline.svg' ,
	'time-outline.svg' ,
	'git-merge-sharp.svg' ,
	'time-sharp.svg' ,
	'git-merge.svg' ,
	'time.svg' ,
	'git-network-outline.svg' ,
	'timer-outline.svg' ,
	'git-network-sharp.svg' ,
	'timer-sharp.svg' ,
	'git-network.svg' ,
	'timer.svg' ,
	'git-pull-request-outline.svg' ,
	'today-outline.svg' ,
	'git-pull-request-sharp.svg' ,
	'today-sharp.svg' ,
	'git-pull-request.svg' ,
	'today.svg' ,
	'glasses-outline.svg' ,
	'toggle-outline.svg' ,
	'glasses-sharp.svg' ,
	'toggle-sharp.svg' ,
	'glasses.svg' ,
	'toggle.svg' ,
	'globe-outline.svg' ,
	'trail-sign-outline.svg' ,
	'globe-sharp.svg' ,
	'trail-sign-sharp.svg' ,
	'globe.svg' ,
	'trail-sign.svg' ,
	'golf-outline.svg' ,
	'train-outline.svg' ,
	'golf-sharp.svg' ,
	'train-sharp.svg' ,
	'golf.svg' ,
	'train.svg' ,
	'grid-outline.svg' ,
	'transgender-outline.svg' ,
	'grid-sharp.svg' ,
	'transgender-sharp.svg' ,
	'grid.svg' ,
	'transgender.svg' ,
	'hammer-outline.svg' ,
	'trash-bin-outline.svg' ,
	'hammer-sharp.svg' ,
	'trash-bin-sharp.svg' ,
	'hammer.svg' ,
	'trash-bin.svg' ,
	'hand-left-outline.svg' ,
	'trash-outline.svg' ,
	'hand-left-sharp.svg' ,
	'trash-sharp.svg' ,
	'hand-left.svg' ,
	'trash.svg' ,
	'hand-right-outline.svg' ,
	'trending-down-outline.svg' ,
	'hand-right-sharp.svg' ,
	'trending-down-sharp.svg' ,
	'hand-right.svg' ,
	'trending-down.svg' ,
	'happy-outline.svg' ,
	'trending-up-outline.svg' ,
	'happy-sharp.svg' ,
	'trending-up-sharp.svg' ,
	'happy.svg' ,
	'trending-up.svg' ,
	'hardware-chip-outline.svg' ,
	'triangle-outline.svg' ,
	'hardware-chip-sharp.svg' ,
	'triangle-sharp.svg' ,
	'hardware-chip.svg' ,
	'triangle.svg' ,
	'headset-outline.svg' ,
	'trophy-outline.svg' ,
	'headset-sharp.svg' ,
	'trophy-sharp.svg' ,
	'headset.svg' ,
	'trophy.svg' ,
	'heart-circle-outline.svg' ,
	'tv-outline.svg' ,
	'heart-circle-sharp.svg' ,
	'tv-sharp.svg' ,
	'heart-circle.svg' ,
	'tv.svg' ,
	'heart-dislike-circle-outline.svg' ,
	'umbrella-outline.svg' ,
	'heart-dislike-circle-sharp.svg' ,
	'umbrella-sharp.svg' ,
	'heart-dislike-circle.svg' ,
	'umbrella.svg' ,
	'heart-dislike-outline.svg' ,
	'unlink-outline.svg' ,
	'heart-dislike-sharp.svg' ,
	'unlink-sharp.svg' ,
	'heart-dislike.svg' ,
	'unlink.svg' ,
	'heart-half-outline.svg' ,
	'videocam-off-outline.svg' ,
	'heart-half-sharp.svg' ,
	'videocam-off-sharp.svg' ,
	'heart-half.svg' ,
	'videocam-off.svg' ,
	'heart-outline.svg' ,
	'videocam-outline.svg' ,
	'heart-sharp.svg' ,
	'videocam-sharp.svg' ,
	'heart.svg' ,
	'videocam.svg' ,
	'help-buoy-outline.svg' ,
	'volume-high-outline.svg' ,
	'help-buoy-sharp.svg' ,
	'volume-high-sharp.svg' ,
	'help-buoy.svg' ,
	'volume-high.svg' ,
	'help-circle-outline.svg' ,
	'volume-low-outline.svg' ,
	'help-circle-sharp.svg' ,
	'volume-low-sharp.svg' ,
	'help-circle.svg' ,
	'volume-low.svg' ,
	'help-outline.svg' ,
	'volume-medium-outline.svg' ,
	'help-sharp.svg' ,
	'volume-medium-sharp.svg' ,
	'help.svg' ,
	'volume-medium.svg' ,
	'home-outline.svg' ,
	'volume-mute-outline.svg' ,
	'home-sharp.svg' ,
	'volume-mute-sharp.svg' ,
	'home.svg' ,
	'volume-mute.svg' ,
	'hourglass-outline.svg' ,
	'volume-off-outline.svg' ,
	'hourglass-sharp.svg' ,
	'volume-off-sharp.svg' ,
	'hourglass.svg' ,
	'volume-off.svg' ,
	'ice-cream-outline.svg' ,
	'walk-outline.svg' ,
	'ice-cream-sharp.svg' ,
	'walk-sharp.svg' ,
	'ice-cream.svg' ,
	'walk.svg' ,
	'id-card-outline.svg' ,
	'wallet-outline.svg' ,
	'id-card-sharp.svg' ,
	'wallet-sharp.svg' ,
	'id-card.svg' ,
	'wallet.svg' ,
	'image-outline.svg' ,
	'warning-outline.svg' ,
	'image-sharp.svg' ,
	'warning-sharp.svg' ,
	'image.svg' ,
	'warning.svg' ,
	'images-outline.svg' ,
	'watch-outline.svg' ,
	'images-sharp.svg' ,
	'watch-sharp.svg' ,
	'images.svg' ,
	'watch.svg' ,
	'infinite-outline.svg' ,
	'water-outline.svg' ,
	'infinite-sharp.svg' ,
	'water-sharp.svg' ,
	'infinite.svg' ,
	'water.svg' ,
	'information-circle-outline.svg' ,
	'wifi-outline.svg' ,
	'information-circle-sharp.svg' ,
	'wifi-sharp.svg' ,
	'information-circle.svg' ,
	'wifi.svg' ,
	'information-outline.svg' ,
	'wine-outline.svg' ,
	'information-sharp.svg' ,
	'wine-sharp.svg' ,
	'information.svg' ,
	'wine.svg' ,
	'invert-mode-outline.svg' ,
	'woman-outline.svg' ,
	'invert-mode-sharp.svg' ,
	'woman-sharp.svg' ,
	'invert-mode.svg' ,
	'woman.svg'
];

export const ICONS_SCHOOL_PACK = {
	name    : 'Back To School' ,
	slug    : 'back-to-school' ,
	viewBox : '0 0 512 512' ,
	width   : null ,
	height  : null ,
	icons   : [
		'Pencil.svg' ,
		'Blackboard.svg' ,
		'Crayon.svg' ,
		'Notebooks.svg' ,
		'Sandwich.svg' ,
		'Folder.svg' ,
		'Soccer-ball.svg' ,
		'Set-square.svg' ,
		'Sharpener.svg' ,
		'Paint-brush.svg' ,
		'Milk.svg' ,
		'School-bus.svg' ,
		'Clock.svg' ,
		'Physics.svg' ,
		'Apple.svg' ,
		'Calculator.svg' ,
		'Highlighter.svg' ,
		'Medal.svg' ,
		'Diploma.svg' ,
		'Backpack.svg' ,
		'Trophy.svg' ,
		'Test.svg' ,
		'Pencil-case.svg' ,
		'Coffee-cup.svg' ,
		'Smartphone.svg' ,
		'Compass.svg' ,
		'Laptop.svg' ,
		'Paint-palette.svg' ,
		'Chat.svg' ,
		'Presentation.svg' ,
		'Flask.svg' ,
		'Eraser.svg' ,
		'Glue.svg' ,
		'Scissors.svg' ,
		'Book.svg' ,
		'Earth-globe.svg' ,
		'Push-pin.svg' ,
		'American-football.svg' ,
		'Compact-disc.svg' ,
		'Desk-lamp.svg' ,
		'Fire-extinguisher.svg' ,
		'Flags.svg' ,
		'Idea.svg' ,
		'Map.svg' ,
		'Pizza.svg' ,
		'Portfolio.svg' ,
		'Ruler.svg' ,
		'Basketball.svg' ,
		'School-bell.svg' ,
		'Sweater.svg'
	]
};

export const ICONS_E_LEARNING_PACK = {
	name    : 'ELearning' ,
	slug    : 'bg-e-learning' ,
	viewBox : '0 0 1600 1200' ,
	width   : '1600' ,
	height  : '1200' ,
	icons   : [
		'bg-e-learning.svg'
	]
};

export const ICONS_ARROW_COLLECTION_PACK = {
	name    : 'Arrow collection' ,
	slug    : 'arrow-collection' ,
	viewBox : '"0 0 52 52' ,
	width   : '' ,
	height  : '' ,
	icons   : [
		'Arrows-1.svg',
		'Arrows-2.svg',
		'Arrows.svg',
		'Back.svg',
		'Backspace.svg',
		'Backward.svg',
		'Center-align.svg',
		'Circuit-1.svg',
		'Circuit-10.svg',
		'Circuit-11.svg',
		'Circuit-2.svg',
		'Circuit-3.svg',
		'Circuit-4.svg',
		'Circuit-5.svg',
		'Circuit-6.svg',
		'Circuit-7.svg',
		'Circuit-8.svg',
		'Circuit-9.svg',
		'Circuit.svg',
		'Compress.svg',
		'Curve-arrow-.svg',
		'Curve-arrow-1.svg',
		'Curve-arrow-2.svg',
		'Curve-arrow-3.svg',
		'Curve-arrow-4.svg',
		'Curve-arrow-6.svg',
		'Curve-arrow-7.svg',
		'Curve-arrow-8.svg',
		'Curve-arrow-9.svg',
		'Curve-arrow.svg',
		'Cycle.svg',
		'Diagonal-1.svg',
		'Diagonal-2.svg',
		'Diagonal-arrow-.svg',
		'Diagonal-arrow-1.svg',
		'Diagonal-arrow-10.svg',
		'Diagonal-arrow-2.svg',
		'Diagonal-arrow-3.svg',
		'Diagonal-arrow-4.svg',
		'Diagonal-arrow-6.svg',
		'Diagonal-arrow-7.svg',
		'Diagonal-arrow-8.svg',
		'Diagonal-arrow-9.svg',
		'Diagonal-arrow.svg',
		'Diagonal.svg',
		'Divide-1.svg',
		'Divide-2.svg',
		'Divide-3.svg',
		'Divide.svg',
		'Down-arrow-1.svg',
		'Down-arrow-2.svg',
		'Down-arrow-3.svg',
		'Down-arrow-4.svg',
		'Down-arrow-5.svg',
		'Down-arrow-6.svg',
		'Down-arrow.svg',
		'Download-1.svg',
		'Download-2.svg',
		'Download-3.svg',
		'Download-4.svg',
		'Download.svg',
		'Drag-1.svg',
		'Drag-10.svg',
		'Drag-11.svg',
		'Drag-2.svg',
		'Drag-3.svg',
		'Drag-4.svg',
		'Drag-5.svg',
		'Drag-6.svg',
		'Drag-7.svg',
		'Drag-8.svg',
		'Drag-9.svg',
		'Drag.svg',
		'Expand-.svg',
		'Expand-1.svg',
		'Expand-2.svg',
		'Expand-3.svg',
		'Expand-4.svg',
		'Expand-6.svg',
		'Expand-7.svg',
		'Expand-8.svg',
		'Expand.svg',
		'Fast-forward.svg',
		'Focus-1.svg',
		'Focus.svg',
		'Forward-1.svg',
		'Forward-2.svg',
		'Forward.svg',
		'Horizontal-arrows.svg',
		'Horizontal.svg',
		'Import.svg',
		'Left-arrow-1.svg',
		'Left-arrow-2.svg',
		'Left-arrow-3.svg',
		'Left-arrow-4.svg',
		'Left-arrow-5.svg',
		'Left-arrow-6.svg',
		'Left-arrow-7.svg',
		'Left-arrow-8.svg',
		'Left-arrow.svg',
		'Minimize.svg',
		'Move-1.svg',
		'Move-2.svg',
		'Move-3.svg',
		'Move.svg',
		'Multiply-1.svg',
		'Multiply-2.svg',
		'Multiply-3.svg',
		'Multiply-4.svg',
		'Multiply-5.svg',
		'Multiply-6.svg',
		'Multiply-7.svg',
		'Multiply-8.svg',
		'Multiply.svg',
		'Orbit-1.svg',
		'Orbit.svg',
		'Reload.svg',
		'Repeat.svg',
		'Return-1.svg',
		'Return-2.svg',
		'Return-3.svg',
		'Return.svg',
		'Rewind.svg',
		'Right-arrow-1.svg',
		'Right-arrow-10.svg',
		'Right-arrow-2.svg',
		'Right-arrow-3.svg',
		'Right-arrow-4.svg',
		'Right-arrow-5.svg',
		'Right-arrow-6.svg',
		'Right-arrow-7.svg',
		'Right-arrow-8.svg',
		'Right-arrow-9.svg',
		'Right-arrow.svg',
		'Shuffle-1.svg',
		'Shuffle-2.svg',
		'Shuffle-3.svg',
		'Shuffle.svg',
		'Spin.svg',
		'Symbiosis-1.svg',
		'Symbiosis-2.svg',
		'Symbiosis-3.svg',
		'Symbiosis.svg',
		'Synchronization.svg',
		'Transfer-1.svg',
		'Transfer.svg',
		'Up-arrow-.svg',
		'Up-arrow-1.svg',
		'Up-arrow-2.svg',
		'Up-arrow-3.svg',
		'Up-arrow-4.svg',
		'Up-arrow-6.svg',
		'Up-arrow-7.svg',
		'Up-arrow.svg',
		'Upload-1.svg',
		'Upload-2.svg',
		'Upload.svg',
		'Upward.svg',
		'Vertical-1.svg',
		'Vertical.svg'
	]
};
